### ISSUE TITLE
Each download item requires selecting the download destination

### ISSUE THREAD

**Issue by james-d-lightfoot** [downthemall/downthemall#345] opened 2021-07-30 22:22 UTC
**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser and version: [Chrome 92.0.4515.107 (Official Build) (64-bit)]
 - DownThemAll! version: [e.g. 4.2.6]

**Describe the bug**
Even when entering a "Subfolder", each download item displays the popup showing the download item's details & default settings requiring a click to start each download.

**To Reproduce**

**Expected behavior**
In the past versions, all downloads auto-initiated, 4 at a time, to the default location

**Screenshots**

**Additional context**

**Comment by d7415** [comment] 2021-07-30 22:38
Duplicate of #168

**Comment by nmaier** [comment] 2021-11-21 16:19
Yeah, probably #168. Can you make sure  the browser setting is configured correctly *not* to always ask?

![Chrome Ask Always](https://user-images.githubusercontent.com/383665/142770107-0b096b99-a3dc-40f2-87ab-1c0874fba4b0.png)

**Closed by nmaier** 2021-11-21 16:19 UTC
