### ISSUE TITLE
Fails to recognise images when the URL has additional parameters

### ISSUE THREAD

**Issue by pF-arQon** [downthemall/downthemall#291] opened 2020-11-16 03:12 UTC
FF82, DTA 4.2.6

On this page:
https://www.webtoons.com/en/fantasy/your-throne/ep-29-i-can-hear-the-heartbeat/viewer?title_no=2009&episode_no=29
the image URLs all have extra data after them, like so:
https://webtoon-phinf.pstatic.net/20200820_285/1597923484996VOvny_JPEG/15979234815462009224.jpg?type=q90

DTA fails to identify any of them *as* images if the "JPEG" or "All Images" boxes are ticked: only "all files" works.

**Expected behavior**
It works?  :)

WAG, the parsing is simply "*.jpg$". It needs to be a bit smarter than that.

**Comment by d7415** [comment] 2020-11-16 12:33
Duplicate of #193 
Workaround in https://github.com/downthemall/downthemall/issues/193#issuecomment-578076851

**Closed** 2020-12-16 16:31 UTC
