### ISSUE TITLE
DTA Not working in Firefox

### ISSUE THREAD

**Issue by FDNY8231** [downthemall/downthemall#169] opened 2019-10-13 16:51 UTC
Windows 10 64-bit
Firefox Quantum V69.0.3
DTA V4.2.2

I can't get DTA to work at all with Firefox. The Manager window opens when I select files to download (say photos) the download screen comes up with my selected files/links but when I click download it does NOTHING at all. ADDING a file from a link does the same exact thing NOTHING. Hasn't worked in Firefox since the re-introduction. 

Works good in Chrome, but I HATE Chrome .... 

Any ideas?

Thanks

**Comment by nmaier** [comment] 2019-10-13 16:57
Do you have permanent private browsing on by chance?

**Comment by nmaier** [comment] 2019-10-13 17:02
If not, then please see: https://github.com/downthemall/downthemall/wiki/Debug-log

**Comment by FDNY8231** [comment] 2019-10-13 17:04
> 
> 
> Do you have permanent private browsing on by chance?

That would be NO

**Comment by FDNY8231** [comment] 2019-10-13 17:09
> 
> 
> If not, then please see: https://github.com/downthemall/downthemall/wiki/Debug-log

This is the report on trying a new download ....

TypeError: a is null
memoize.ts:55:6
TypeError: Argument 1 of PrecompiledScript.executeInGlobal is not an object.
4 ExtensionContent.jsm:554:25
NotFoundError: The operation failed because the requested database object could not be found. For example, an object store did not exist but was being opened. DOMException: "The operation failed because the requested database object could not be found. For example, an object store did not exist but was being opened." windowutils.ts:104:12
TypeError: a is null
memoize.ts:55:6
Unchecked lastError value: Error: Missing host permission for the tab, and any iframes background_ff2.js:1
TypeError: a is null
memoize.ts:55:6
Unchecked lastError value: Error: Missing host permission for the tab, and any iframes background_ff2.js:1
[Exception... "Component not initialized"  nsresult: "0xc1f30001 (NS_ERROR_NOT_INITIALIZED)"  location: "JS frame :: resource://gre/modules/ExtensionChild.jsm :: api/register/publicAPI.onDisconnect< :: line 215"  data: no]
api/register/publicAPI.onDisconnect<@resource://gre/modules/ExtensionChild.jsm:215:42
listener@resource://gre/modules/ExtensionChild.jsm:272:9
disconnectByOtherEnd@resource://gre/modules/ExtensionChild.jsm:353:7
receiveMessage@resource://gre/modules/ExtensionChild.jsm:181:44
_handleMessage/</<@resource://gre/modules/MessageChannel.jsm:962:27
_handleMessage/<@resource://gre/modules/MessageChannel.jsm:961:9
_handleMessage@resource://gre/modules/MessageChannel.jsm:959:16
receiveMessage/<@resource://gre/modules/MessageChannel.jsm:225:14
receiveMessage@resource://gre/modules/MessageChannel.jsm:218:10
MessageChannel.jsm:964
NotFoundError: The operation failed because the requested database object could not be found. For example, an object store did not exist but was being opened.

**Comment by nmaier** [comment] 2019-10-13 17:14
It cannot open the DB for whatever reason. 
I'd suggest you try a new profile and see if that works: https://support.mozilla.org/en-US/kb/profile-manager-create-remove-switch-firefox-profiles

**Comment by nmaier** [comment] 2019-10-13 17:14
>It cannot open the DB for whatever reason.

This is most likely a Firefox bug.

**Comment by FDNY8231** [comment] 2019-10-13 17:22
I could agree with you If I wasn't the only FF user making a post like this. 

Is it possible another download manager could be conflicting with DTA? 

In the absence of DTA I found a AntDownloadManager wich works fine, but I wonder if that could now be conflicting.

**Comment by nmaier** [comment] 2019-10-13 17:24
>I could agree with you If I wasn't the only FF user making a post like this.

So far you are the only one reporting *exactly*  this issue (other DB issues had different causes).

>Is it possible another download manager could be conflicting with DTA?

No

**Comment by FDNY8231** [comment] 2019-10-13 17:28
> 
> 
> > I could agree with you If I wasn't the only FF user making a post like this.
> 
> So far you are the only one reporting _exactly_ this issue (other DB issues had different causes).
> 
> > Is it possible another download manager could be conflicting with DTA?
> 
> No, or at least extremely, extremely unlikely.

I thought it might be worth an ask, but I agree ... 
The new profile for me is NOT an option unless a crash occurred and I would need to begin from scratch.

**Comment by nmaier** [comment] 2019-10-13 17:29
The new profile is to see if it works at all on your system. You do not need to throw your old profile away.

**Comment by FDNY8231** [comment] 2019-10-13 17:39
> 
> 
> The new profile is to see if it works at all on your system. You do not need to throw your old profile away.

Okay tried the new profile at it worked with the following in the debug console

starting Download(https://www.downthemall.org/images/spot/press.png) 
Object { state: 1, url: "https://www.downthemall.org/images/spot/press.png", usable: "https://www.downthemall.org/images/spot/press.png", referrer: "https://www.downthemall.org/images/spot/press.png", usableReferrer: "https://www.downthemall.org/images/spot/press.png", fileName: "", mask: "*name*.*ext*", subfolder: "", batch: 1, idx: 1, … }
download.ts:116:12

**Comment by nmaier** [comment] 2019-10-13 17:57
Well, that suggests something in your old profile is broken... I couldn't say what (without sitting in front of it, poking and prodding at it). It might be some browser preference with an unexpected value (things changed through about:config are good candidates), it might be some corrupted files in there, or an antivirus going rampage on it locking files, or something else in there interfering like a third party software that "integrated" itself (tho other add-ons, as I said, are extremely unlikely to interfere as Firefox isolates WebExtensions from each other, but still some other add-on may trigger a bug in Firefox itself which then affects DownThemAll! as well, unlikely but possible).

And I don't think you want to give me a copy of your profile to see if I can reproduce it. Too much personal data in there. 😉 

Your options, as far as I see:
- Use a new profile (and port over the interesting data such as bookmarks, logins, etc, from the old one). The internet has a lot of info about it, and mozilla has support forums. You could e.g. try to copy everything in your old profile to a new profile and then use [Refresh Firefox](https://support.mozilla.org/en-US/kb/refresh-firefox-reset-add-ons-and-settings) in that new profile and see if that helps.
- Use a new profile only for DownThemAll! (you can run multiple Firefox profiles at the same time; the internet knows more)
- Do not use DownThemAll! and hope it was the only thing affected by whatever is going on in your old profile.

Since we now determined that there is something wrong in your current Firefox profile at interferes with DownThemAll!, as a new profile works just fine, and since DownThemAll! cannot fix such things, I am going to close this issue now.

Sorry I couldn't help more.

**Closed by nmaier** 2019-10-13 17:57 UTC
