### ISSUE TITLE
Download directory

### ISSUE THREAD

**Issue by Screemer1** [downthemall/downthemall#237] opened 2020-04-22 11:39 UTC
As I want to use DTA I would like to be able to use different download directories for each download.
Now it seem to use Windows default download directory as base even though I have changed that.

I think it would be nice to have the option to be able to chose the entire download dir path for each download, even UNC paths if I want to.

Would it be possible to fix this for an upcoming release?

**Comment by d7415** [comment] 2020-04-22 15:37
Duplicate of #2

**Comment by nmaier** [comment] 2020-05-14 13:00
#2

**Closed by nmaier** 2020-05-14 13:00 UTC
