### ISSUE TITLE
Davis

### ISSUE THREAD

**Issue by Davis965** [downthemall/downthemall#60] opened 2019-09-03 19:11 UTC
**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox
 - Version 69

**Describe the bug**

    - Users cannot select the location or folder to download the files. Old version had a feature to select the location.

    - After using DownThemAll, Firefox's default size changes.

**Comment by d7415** [comment] 2019-09-03 21:09
> - Users cannot select the location or folder to download the files. Old version had a feature to select the location.

Duplicate of #2. See that issue for workarounds.

> - After using DownThemAll, Firefox's default size changes.

I'm not sure what you mean here.


For future issues, please put a short description of the problem in the title, rather than your name.

**Comment by nmaier** [comment] 2019-09-04 01:11
Yes, #2 

>After using DownThemAll, Firefox's default size changes.

Please refile this with more information

**Closed by nmaier** 2019-09-04 01:11 UTC
Labels: duplicate
