### ISSUE TITLE
Catch DEB Files

### ISSUE THREAD

**Issue by MichWeb75** [downthemall/downthemall#373] opened 2022-02-11 12:05 UTC
I am using Ubuntu 18 with Firefox 96 and downthemall Extension 4.3.1

Dear developers,
I am not able to get simple files get tracked by downthemall. For example going to
 https://www.opera.com/download will download opera-stable_83.0.4254.54_amd64.deb
But this file is managed by Firefox and not listed in the Downthemall list. How to configure Downthemall to track this file ?

Best, Michael

**Comment by d7415** [comment] 2022-02-11 21:08
That link has redirects, the URLs on the page don't say that it's a .deb, so that can't be detected by DTA. If you're looking for DTA to step in after the link has been clicked, it's probably a duplicate of #18.

**Comment by nmaier** [comment] 2022-06-20 11:54
Yeah, #18 seems right

**Closed by nmaier** 2022-06-20 11:54 UTC
Labels: duplicate
