### ISSUE TITLE
Add download option in the download box like in the old version

### ISSUE THREAD

**Issue by dudefoxlive** [downthemall/downthemall#240] opened 2020-05-07 16:10 UTC
So I remember back before firefox screwed all the extensions over when I would download a file DownThemAll was an option in the download dialog. I was hoping this can be added back as I now forget that this extension is installed because it does not appear there anymore. I have attached a picture of the dialog I am referring to. 
![image](https://user-images.githubusercontent.com/50186495/81318041-a2719d80-905b-11ea-9089-b96ccfd2a680.png)

**Comment by d7415** [comment] 2020-05-07 16:42
Duplicate of #18

**Comment by nmaier** [comment] 2020-05-14 13:00
#18

**Closed by nmaier** 2020-05-14 13:00 UTC
