### ISSUE TITLE
Duplicating extensions and opening save as window

### ISSUE THREAD

**Issue by nbcjr** [downthemall/downthemall#296] opened 2020-11-23 14:30 UTC
**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser and version: Chrome 86.0.4240.198 
 - DownThemAll! version: latest

**Describe the bug**

Whenever I add links, the extensions always gets duplicated, and even worse, a save as windows always open to confirm the download, which completely makes Downthemall not useful to me.

**To Reproduce**
add link. for example the installer on this link https://archive.mozilla.org/pub/firefox/releases/52.9.0esr/win64/en-US/
<img width="1070" alt="2020-11-23 14_28_34-11 49% _ Synchronizing  _  Last session  _ 23_11_2020 14_09_34" src="https://user-images.githubusercontent.com/74916914/99974067-5a685d00-2d98-11eb-8fe3-bd3b46cf1824.png">

**Expected behavior**
download without user intervention

**Screenshots**
added screenshot

**Comment by d7415** [comment] 2020-11-23 15:04
The second part (the save as window) looks like a duplicate of #168.

I'm not sure about the double extensions. What renaming mask are you using? `*name*.*ext*`?

**Comment by nbcjr** [comment] 2020-11-23 19:56
Thank you, you have nailed the save as.  I know you can't change this, but Maybe make clearer this behaviour somehow?

please close the issue.

**Comment by d7415** [comment] 2020-11-23 20:03
I'm not actually the maintainer - you should be able to close the issue yourself though. Otherwise at least this one should be quick for Nils!

**Closed** 2020-11-24 19:02 UTC
