### ISSUE TITLE
Accumulating cache files?

### ISSUE THREAD

**Issue by nji9nji9** [downthemall/downthemall#456] opened 2023-06-04 15:15 UTC
I recently discovered and installed dTa,
a few days later I found that in
C:\Users\<User>\AppData\Local\Microsoft\Windows\WebCache
there are about a dozen of 512 kB sized files named
V01000??.log and
V01res0000?.jrs
Moreover a 32 MB sized file WebCacheV01.dat

I'm not completely sure, but do suspect they are created by dTa.

They aren't deleted when deleting the chronic of the browser
or if I de-activate dTa.

A bug in dTa then?

Win7-64 SP1, FF 102.11.0esr (64-Bit), dTa 4.10.1

**Comment by nmaier** [comment] 2023-08-23 19:31
If anything, this data would be created by a browser, and given the folder location it can only be a Microsoft browser. DownThemAll! wouldn't have any say in how such a browser managed their caches.

According to a google search, it might be actually Windows itself creating these files, tho, not even a browser.
See: https://superuser.com/questions/1600395/what-is-the-webcache-folder-in-appdata-local-microsoft-windows-windows-10

To be clear. DownThemAll! does not even have access to such a location on your system. It is restricted to whatever Downloads folder the browser it is running in has configured (usually the "Downloads" folder), and it can only put data, or rather tell the browser to put data there, there but not read data from it[1].

As such, as this isn't caused by DownThemAll!, I am closing this ticket.

[1] Unless the user specifically hands data to it, e.g. through the "import" menu. This is regulated by the browser as a security feature, so that extensions cannot steal your data. Not that DTA would ever want to steal your data, of course

**Closed by nmaier** 2023-08-23 19:31 UTC
