### ISSUE TITLE
DTA Manager

### ISSUE THREAD

**Issue by melzas777** [downthemall/downthemall#298] opened 2020-11-25 14:09 UTC
How to integrate DTA Manager into default download option in Firefox 78.5 ESR, like with Classic versions of Firefox?

**Comment by d7415** [comment] 2020-11-25 17:12
Duplicate of #18 (Which is pinned above the issues list)

**Comment by nmaier** [comment] 2020-12-16 16:19
#18

**Closed by nmaier** 2020-12-16 16:19 UTC
