### ISSUE TITLE
Download file location

### ISSUE THREAD

**Issue by theromorph** [downthemall/downthemall#281] opened 2020-09-13 13:02 UTC
**Desktop (please complete the following information):**
 - OS: Windows 7, Windows 8.1, Windows Server 2012 R2
 - Browser and version: Chromium 86.0.4185.0 (Official Build) (64-bit), Maxthon 6.1.0.700 (64-bit) (Chromium 85 based)
 - DownThemAll! version: 4.2.6

**Describe the bug**
When I add some download to DTA using OneClick action, it ask confirmation of file location every time it starts for every download.

**To Reproduce**
1. Add some downloads to DTA using OneClick action
2. Download them consequently
3. See annoying confirmation for every download

**Expected behavior**
There should be a clear option for download location (for every filter as an advance)
(As a compromise It could be set via DTA regular download dialog)

**Additional context**
There is no such problem in the DTA for Firefox.
I can't find such option there to set file location for downloads, but at least file location remembered once it set via DTA regular add download dialog.

**Comment by d7415** [comment] 2020-09-13 13:55
Duplicate of #168

**Closed** 2020-12-16 16:43 UTC
