### ISSUE TITLE
Skip if exists

### ISSUE THREAD

**Issue by raybrooksby** [downthemall/downthemall#312] opened 2021-01-23 15:35 UTC
Would like an option that skips the download of the file already exists.

**Comment by mfaizsyahmi** [comment] 2021-04-07 04:40
Looks like DTA development is dead.

**Comment by d7415** [comment] 2021-04-07 09:28
This is a duplicate of #88. As explained there, this is a limitation of WebExtensions.

**Closed** 2021-11-21 17:32 UTC
