### ISSUE TITLE
FIREFOX Right-Click menu request

### ISSUE THREAD

**Issue by whartega** [downthemall/downthemall#301] opened 2020-12-05 11:49 UTC
Not sure if available or previously discussed, but the Firefox DtA extension doesn't seem to allow right-click-menu changes.
Previous DtA versions allowed the right-click menu to show "Save Link with OneClick", now this selection is only accessible after first hovering over "DownThemAll!".

I prefer the ability to have a single right-click on a link to show "Save Link with OneClick" in the right click menu.

**Comment by d7415** [comment] 2020-12-05 12:43
Possibly a duplicate of #248 if you want multiple options. If you just wanted to pick one, that might be possible.

**Comment by whartega** [comment] 2020-12-05 14:20
Yes, thank you; that is exactly the same issue I am having.
Apparently no solution or workaround. <sadface>

**Comment by nmaier** [comment] 2020-12-16 16:17
Indeed, this is behavior browsers dictate and that cannot be changed unless the browsers change their policy

**Closed by nmaier** 2020-12-16 16:17 UTC
